# Generated by Django 4.1.4 on 2022-12-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_qpuserprofile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpuserprofile',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
    ]
