# Generated by Django 4.1.4 on 2022-12-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_qpuserprofile_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpuserprofile',
            name='hide_completed_archwings',
            field=models.BooleanField(default=False, verbose_name='Hide Completed Archwings'),
        ),
        migrations.AddField(
            model_name='qpuserprofile',
            name='hide_completed_companions',
            field=models.BooleanField(default=False, verbose_name='Hide Completed Companions'),
        ),
        migrations.AddField(
            model_name='qpuserprofile',
            name='hide_completed_meleeweapons',
            field=models.BooleanField(default=False, verbose_name='Hide Completed Melee Weapons'),
        ),
        migrations.AddField(
            model_name='qpuserprofile',
            name='hide_completed_primaryweapons',
            field=models.BooleanField(default=False, verbose_name='Hide Completed Primary Weapons'),
        ),
        migrations.AddField(
            model_name='qpuserprofile',
            name='hide_completed_secondaryweapons',
            field=models.BooleanField(default=False, verbose_name='Hide Completed Secondary Weapons'),
        ),
        migrations.AddField(
            model_name='qpuserprofile',
            name='hide_completed_warframes',
            field=models.BooleanField(default=False, verbose_name='Hide Completed Warframes'),
        ),
    ]
