version: "3"

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        # command: daphne -b 0.0.0.0 -p 8000 qp.asgi:application
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - "db"
        env_file: .env
        restart: always

    db:
        image: postgres:14.1-alpine
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_USER=${POSTGRES_USER}"
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
            - "POSTGRES_DB=db"
            - "LANG=fr_CA=utf8"
        volumes:
            - .:/code
