# Generated by Django 4.1.4 on 2022-12-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warframe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='qpUserWarframeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_components', to='warframe.qpwarframecomponent', verbose_name='Component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warframe_components', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Warframe Component',
                'verbose_name_plural': 'Warframe Components',
                'ordering': ['user', 'component'],
            },
        ),
    ]
