# Generated by Django 4.1.4 on 2022-12-21 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0005_qpsecondaryweaponcomponent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companion', '0002_qpuserprimaryweaponcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpUserSecondaryWeaponComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_components', to='warframe.qpsecondaryweaponcomponent', verbose_name='Component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondaryweapon_components', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Secondary Weapon Component',
                'verbose_name_plural': 'Secondary Weapon Components',
                'ordering': ['user', 'component'],
            },
        ),
    ]
