# Generated by Django 4.1.4 on 2022-12-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qpRelic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(choices=[('Lith', 'Lith'), ('Meso', 'Meso'), ('Neo', 'Neo'), ('Axi', 'Axi')], max_length=32, verbose_name='Era')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Relic',
                'verbose_name_plural': 'Relics',
                'ordering': ['era', 'name'],
            },
        ),
        migrations.CreateModel(
            name='qpWarframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('image_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Image Name')),
            ],
            options={
                'verbose_name': 'Warframe',
                'verbose_name_plural': 'Warframes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpWarframeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('blueprint', 'Blueprint'), ('neuroptics', 'Neuroptics'), ('chassis', 'Chassis'), ('systems', 'Systems')], max_length=32, verbose_name='Name')),
                ('warframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='warframe.qpwarframe', verbose_name='Warframe')),
            ],
            options={
                'verbose_name': 'Warframe Component',
                'verbose_name_plural': 'Warframe Components',
                'ordering': ['warframe', 'name'],
            },
        ),
        migrations.CreateModel(
            name='qpWarframeRelicReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0, verbose_name='Drop Chance')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='warframe.qpwarframecomponent', verbose_name='Warframe Component')),
                ('relic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warframe_rewards', to='warframe.qprelic', verbose_name='Relic')),
            ],
            options={
                'verbose_name': 'Warframe Relic Reward',
                'verbose_name_plural': 'Warframe Relic Rewards',
                'ordering': ['component', '-percent'],
            },
        ),
    ]
