# Generated by Django 4.1.4 on 2022-12-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpMeleeWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('image_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Image Name')),
            ],
            options={
                'verbose_name': 'Melee Weapon',
                'verbose_name_plural': 'Melee Weapons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpPrimaryWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('image_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Image Name')),
            ],
            options={
                'verbose_name': 'Primary Weapon',
                'verbose_name_plural': 'Primary Weapons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpSecondaryWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('image_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Image Name')),
            ],
            options={
                'verbose_name': 'Secondary Weapon',
                'verbose_name_plural': 'Secondary Weapons',
                'ordering': ['name'],
            },
        ),
    ]
