# Generated by Django 4.1.4 on 2022-12-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpRelic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(max_length=32, verbose_name='Era')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Relic',
                'verbose_name_plural': 'Relics',
                'ordering': ['name'],
            },
        ),
    ]
