# Generated by Django 4.1.4 on 2022-12-15 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0002_qprelic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qprelic',
            name='era',
            field=models.CharField(choices=[('Lith', 'Lith'), ('Meso', 'Meso'), ('Neo', 'Neo'), ('Axi', 'Axi')], max_length=32, verbose_name='Era'),
        ),
        migrations.CreateModel(
            name='qpWarframeRelicReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('neuroptics', 'Neuroptics'), ('chassis', 'Chassis'), ('systems', 'Systems')], max_length=250, verbose_name='Component')),
                ('percent', models.FloatField(default=0, verbose_name='Drop Chance')),
                ('relic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='warframe.qprelic', verbose_name='Relic')),
                ('warframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='warframe.qpwarframe', verbose_name='Warframe')),
            ],
            options={
                'verbose_name': 'Warframe Relic Reward',
                'verbose_name_plural': 'Warframe Relic Rewards',
                'ordering': ['percent', 'component'],
            },
        ),
    ]
