# Generated by Django 4.1.4 on 2022-12-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0003_alter_qprelic_era_qpwarframerelicreward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qprelic',
            options={'ordering': ['era', 'name'], 'verbose_name': 'Relic', 'verbose_name_plural': 'Relics'},
        ),
        migrations.AlterModelOptions(
            name='qpwarframerelicreward',
            options={'ordering': ['component', '-percent'], 'verbose_name': 'Warframe Relic Reward', 'verbose_name_plural': 'Warframe Relic Rewards'},
        ),
        migrations.AddField(
            model_name='qpwarframe',
            name='image_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Image Name'),
        ),
        migrations.AlterField(
            model_name='qpwarframerelicreward',
            name='component',
            field=models.CharField(choices=[('blueprint', 'Blueprint'), ('neuroptics', 'Neuroptics'), ('chassis', 'Chassis'), ('systems', 'Systems')], max_length=250, verbose_name='Component'),
        ),
    ]
