# Generated by Django 4.1.4 on 2022-12-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0004_alter_qprelic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpwarframerelicreward',
            name='warframe',
        ),
        migrations.AlterField(
            model_name='qpwarframerelicreward',
            name='relic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warframe_rewards', to='warframe.qprelic', verbose_name='Relic'),
        ),
        migrations.CreateModel(
            name='qpWarframeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('blueprint', 'Blueprint'), ('neuroptics', 'Neuroptics'), ('chassis', 'Chassis'), ('systems', 'Systems')], max_length=32, verbose_name='Name')),
                ('warframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='warframe.qpwarframe', verbose_name='Warframe')),
            ],
            options={
                'verbose_name': 'Warframe Component',
                'verbose_name_plural': 'Warframe Components',
                'ordering': ['warframe', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='qpwarframerelicreward',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='warframe.qpwarframecomponent', verbose_name='Warframe Component'),
        ),
    ]
