# Generated by Django 4.1.4 on 2022-12-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0005_qpsecondaryweaponcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpSecondaryWeaponRelicReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0, verbose_name='Drop Chance')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='warframe.qpsecondaryweaponcomponent', verbose_name='Secondary Weapon Component')),
                ('relic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondaryweapon_rewards', to='warframe.qprelic', verbose_name='Relic')),
            ],
            options={
                'verbose_name': 'Secondary Weapon Relic Reward',
                'verbose_name_plural': 'Secondary Weapon Relic Rewards',
                'ordering': ['component', '-percent'],
            },
        ),
    ]
