# Generated by Django 4.1.4 on 2022-12-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0006_qpsecondaryweaponrelicreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpMeleeWeaponComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('blueprint', 'Blueprint'), ('barrel', 'Barrel'), ('blade', 'Blade'), ('grip', 'Grip'), ('handle', 'Handle'), ('link', 'Link'), ('lowerlimb', 'Lower Limb'), ('pouch', 'Pouch'), ('receiver', 'Receiver'), ('stars', 'Stars'), ('stock', 'Stock'), ('string', 'String'), ('upperlimb', 'Upper Limb')], max_length=32, verbose_name='Name')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Count')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='warframe.qpmeleeweapon', verbose_name='Weapon')),
            ],
            options={
                'verbose_name': 'Melee Weapon Component',
                'verbose_name_plural': 'Melee Weapon Components',
                'ordering': ['weapon', 'name'],
            },
        ),
        migrations.AddField(
            model_name='qpprimaryweaponcomponent',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='qpsecondaryweaponcomponent',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='qpwarframecomponent',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='qpprimaryweaponcomponent',
            name='name',
            field=models.CharField(choices=[('blueprint', 'Blueprint'), ('barrel', 'Barrel'), ('blade', 'Blade'), ('grip', 'Grip'), ('handle', 'Handle'), ('link', 'Link'), ('lowerlimb', 'Lower Limb'), ('pouch', 'Pouch'), ('receiver', 'Receiver'), ('stars', 'Stars'), ('stock', 'Stock'), ('string', 'String'), ('upperlimb', 'Upper Limb')], max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='qpsecondaryweaponcomponent',
            name='name',
            field=models.CharField(choices=[('blueprint', 'Blueprint'), ('barrel', 'Barrel'), ('blade', 'Blade'), ('grip', 'Grip'), ('handle', 'Handle'), ('link', 'Link'), ('lowerlimb', 'Lower Limb'), ('pouch', 'Pouch'), ('receiver', 'Receiver'), ('stars', 'Stars'), ('stock', 'Stock'), ('string', 'String'), ('upperlimb', 'Upper Limb')], max_length=32, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='qpMeleeWeaponRelicReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0, verbose_name='Drop Chance')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='warframe.qpmeleeweaponcomponent', verbose_name='Melee Weapon Component')),
                ('relic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meleeweapon_rewards', to='warframe.qprelic', verbose_name='Relic')),
            ],
            options={
                'verbose_name': 'Melee Weapon Relic Reward',
                'verbose_name_plural': 'Melee Weapon Relic Rewards',
                'ordering': ['component', '-percent'],
            },
        ),
    ]
