# Generated by Django 4.1.4 on 2022-12-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0007_qpmeleeweaponcomponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpmeleeweaponcomponent',
            name='count',
        ),
        migrations.RemoveField(
            model_name='qpprimaryweaponcomponent',
            name='count',
        ),
        migrations.RemoveField(
            model_name='qpsecondaryweaponcomponent',
            name='count',
        ),
        migrations.RemoveField(
            model_name='qpwarframecomponent',
            name='count',
        ),
        migrations.AddField(
            model_name='qpmeleeweaponcomponent',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='qpprimaryweaponcomponent',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='qpsecondaryweaponcomponent',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='qpwarframecomponent',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
