# Generated by Django 4.1.4 on 2022-12-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0008_remove_qpmeleeweaponcomponent_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpmeleeweaponcomponent',
            name='quantity_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='qpprimaryweaponcomponent',
            name='quantity_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='qpsecondaryweaponcomponent',
            name='quantity_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='qpwarframecomponent',
            name='quantity_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Count'),
        ),
    ]
